spring.application.name=ai-service
server.port=${AI_SERVICE_PORT:8086}

# IA real (mock apagado)
AI_MOCK_ENABLED=false
OPENAI_API_KEY=${OPENAI_API_KEY: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}
OPENAI_MODEL=${OPENAI_MODEL:gpt-5.4}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
